import type { IconName } from "./Icon";
import {
  APPS_URL,
  ARCHIVE_URL,
  BOOKMARKS_URL,
  FEEDS_URL,
  HISTORY_URL,
  NOTEBOOK_URL,
  OMNI_URL,
  RESOURCES_URL,
  SESSIONS_URL,
  SETTINGS_URL,
  SPEEDTEST_URL,
  SYNC_URL,
  TASKS_URL,
  TRAIL_URL,
  WHITEBOARD_URL,
  SCRIBE_URL,
  VAULT_URL,
} from "./ipc";

export const PAGES: { icon: IconName; label: string; url: string }[] = [
  { icon: "notebook", label: "Notebook", url: NOTEBOOK_URL },
  { icon: "trail", label: "Trail", url: TRAIL_URL },
  { icon: "whiteboard", label: "Whiteboard", url: WHITEBOARD_URL },
  { icon: "scribe", label: "Scribe", url: SCRIBE_URL },
  { icon: "sessions", label: "Sessions", url: SESSIONS_URL },
  { icon: "archive", label: "Saved pages", url: ARCHIVE_URL },
  { icon: "feeds", label: "Feeds", url: FEEDS_URL },
  { icon: "history", label: "History", url: HISTORY_URL },
  { icon: "bookmarks", label: "Bookmarks", url: BOOKMARKS_URL },
  { icon: "tasks", label: "Task manager", url: TASKS_URL },
  { icon: "resources", label: "Resources", url: RESOURCES_URL },
  { icon: "speedtest", label: "Speed test", url: SPEEDTEST_URL },
  { icon: "omni", label: "Omni", url: OMNI_URL },
  { icon: "apps", label: "Apps", url: APPS_URL },
  { icon: "passwords", label: "Passwords", url: VAULT_URL },
  { icon: "sync", label: "Sync", url: SYNC_URL },
  { icon: "settings", label: "Settings", url: SETTINGS_URL },
];
